### ISSUE TITLE
Evolution idea : hide vendors with articles outside my country

### ISSUE THREAD

**Issue by Cyril-Cf** [sometimesdigital/fast-fashion-begone#1]
I've been looking for something like your extension, and I'm glad you decided to share it. Do you think it would be possible to tweak it a little so we can also hide articles from outside our country? I'm tired of looking at articles with shipping fees that would triple the value of the cart, and Vinted doesn't allow such filter.

Still, thanks for the great work!

**Comment by nonnullish** [comment]
Hi, thanks for the feature proposal and the kind words! Sadly, I don't think this would be possible, as this information isn't available in the view. 

The only solution I can think of would be searching for the name of the article in your language and hoping that that would not get autotranslated or that users from other countries wouldn't put that word in the article name.

**Comment by Cyril-Cf** [comment]
Oh, I thought we could do something about it, I played around a little with Vinted API and the information about the seller's origin was in there, I guess it's not used to display the list, I'm not very good at it, I first thought we could use that to hide unwanted articles. Too bad, thanks for letting me know :)

**Comment by nonnullish** [comment]
The way this extension works is very simple - it just goes through the DOM and removes the elements that contain the selected strings -- so I didn't need to mess with the Vinted API, but I'd be curious about your approach if you decided to do it that way :)
