### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by raao29** [sometimesdigital/fast-fashion-begone#2]
it stopped working since last week can you look at it please?

**Comment by nonnullish** [comment]
hey, thanks for letting me know :) I've made a fix but I'm currently locked out of my Firefox account so I can't publish the update just yet. should be up soon hopefully

**Comment by jamesblonde007** [comment]
Was about to post the same issue but I see you are already on the case. Hope you can get back into your Firefox account!

**Comment by nonnullish** [comment]
@raao29, @jamesblonde007 - finally I managed to [upload the update (version 0.3)](https://addons.mozilla.org/en-GB/firefox/addon/fast-fashion-begone/). let me know if it works!

**Comment by jamesblonde007** [comment]
Seems to be working, Thanks!
