### ISSUE TITLE
No longer working after Vinted site redesign

### ISSUE THREAD

**Issue by jamesblonde007** [sometimesdigital/fast-fashion-begone#3]
It looks as if Vinted has updated its website, with several UI changes, and that the plug-in no longer works.

**Comment by nonnullish** [comment]
hmm, I guess they haven't rolled out the updates for everyone yet because it works for me still.
can you let me know which country you're accessing?

**Comment by jamesblonde007** [comment]
> hmm, I guess they haven't rolled out the updates for everyone yet because it works for me still. can you let me know which country you're accessing?

Italy

**Comment by jamesblonde007** [comment]
You will be able to identify the new UI when you look at an item listing. The "add to favourites" button is no longer there. Instead there is a clickable heart icon over the bottom right corner of the product photo.

**Comment by nonnullish** [comment]
should be fixed now! the new version (0.4) is already in the [Firefox Browser Add-Ons](https://addons.mozilla.org/en-GB/firefox/addon/fast-fashion-begone/).
thanks for letting me know about the issue!

**Comment by jamesblonde007** [comment]
Great, thanks for the fast update!
