### ISSUE TITLE
limit to amount of brands

### ISSUE THREAD

**Issue by studystudy92** [sometimesdigital/fast-fashion-begone#4]
when i copy paste a huge list of brands (1000+) it doesnt get saved. is there a limit of amount of brands you can exclude?if so, would be helpful to remove this limit. can you help

thanks

**Comment by nonnullish** [comment]
hey! wow I haven't tested it for cases like that but I can try to see why it doesn't get saved. can you send me the list so that I can test it? here in a comment or email me at nonnullish@sometimes.digital

**Comment by studystudy92** [comment]
Burberry, Boss, Ba&sh, Barbour, Balenciaga, Bonpoint, Bugatti, Belstaff,
Balmain, BCBGMAXAZRIA, Blumarine, BMW, Bogner, Borbonese, Bally, Burberrys,
Baldinini, Bottega Veneta, Bershka, Boohoo, Butik, Bonobo, Bizzbee, Barbie,
Baby Club, Bout'chou, Bonprix, Blanco, Bodyflirt, Baby, Bata, Bundle,
Bréal, Blukids, Blancheporte, Brice, Bik Bok, Bench, Brave Soul, Black,
Batman, Bóboli, Bel&Bo, bpc bonprix collection, Bandai, Bijou Brigitte,
Bambina, Big Star, Bambino, Brums, Blue Seven, beloved, BoohooMAN, Boots,
Bonmarché, Best Mountain, Blue Motion, Bhs, Bleu, BÉABA, Boîte À Malices,
Basic, Bianco, Banana Moon, Blu, Blue, Babymoov, Bianca, Bonita, B.P.C,
Bel-Air, Boys, Blind Date, b.young, Babyface, Bambini, Blend, By o la
la...!, B'Twin, B.Nosy, BIMBO, BIBA, bellybutton, BELLAMY, BTS, Build A
Bear Workshop, Blue Vanilla, BPC Selection, Besson, BLANC, Bilook, Bestway,
Bébé Rêve, B&M, Bob der Bär, BZB, Baby by Gémo, Blue Ridge, Befado, Brugi,
B&C, Bratz, Bobo Choses, Brotes, Bartek, Bleu bonheur, Banpresto, Brioche,
Bellissima, BESS, Bakkaboe, Baby Born, Bom, Barts, Billie Faiers,
Boomerang, Buissonnière, Broadway, Bronx, Brosway, Black Bananas, Bonton,
Blouse, Babystyling, Bornino, Bburago, Biaggini, Boy, bopy, babidu, Bien
Bleu, BESTies, Bordeaux, Bisou's Project, Baby Girl, Bexleys, Billie &
Blossom, Basic One, Betty Boop, badabulle, Bing, By Clara, Burga, Bella,
Blanc du Nil, Boutique Ware, Bobbi Shoes, Biedronka, Blanche, Blanca,
Berna, Babydream, Babylove, Bear, Black Squad, Bluey, BRUNOTTI, Butterfly,
Baby Nat, Bellissimo, BABY Blue, Blutsgeschwister, Bébé 9, BM, Bruder,
Belle, Berlingot, BnK, Bullboxer, Bubble Gum, Boutique Belgique, bama,
Bavaria, BIC, Born2be, Bay, Bright Starts, BKL Wear, Blooshop, Beckaro,
Baylis & Harding, Brandy Melville, Boutique Parisienne, Boden, Billabong,
Burton, Bimba Y Lola, Birkenstock, Bebe, Buffalo, Bimba, Banana Republic,
BaByliss, BabyGap, Brownie, Ben Sherman, Betty Barclay, Boutique privée,
Berghaus, Bellerose, BDG, Babybjörn, Billieblush, Bébé Confort, Bugaboo,
Boux Avenue, Blauer, Berenice, Bensimon, Bocage, Breil, Bikkembergs,
Bo+Tee, BRAX, Byblos, BOY London, Babolat, Bisgaard, Babybotte,
Biomecanics, Björn Borg, Broken Planet Market, Benefit, Burton Menswear
London, Bering, Braccialini, BOBUX, Brooks, Braun, Bloch, Bouchara,
Bandolera, Baci&Abbracci, Basler, Balducci, Bytom, Bruno Banani, Brio,
adidas, ASOS, Atmosphere, Amisu, Abercrombie & Fitch, Amazon, Armani,
Asics, Alcott, Absorba, Armand Thiery, adidas Originals, Apple, AVON,
Accessorize, Alana, American Vintage, AllSaints, Armani Jeans, André, Anna
Field, Air Force, AX Paris, America Today, Action, Argento, ALDO, American
Eagle, Apricot, Alternative, Airness, Adolfo Dominguez, alive, Antony
Morato, Angelo Litrico, Artigli, Autograph, Abendkleid, Arena, Argent,
ARKET, Auchan, Armani Exchange, Aigle, Avent, Aldi, Ann Summers, Alexander
McQueen, Animal, Artengo, Asda, American Apparel, Alviero Martini, Acciaio,
ASH, Atmosphera, Aéropostale, an'ge, ABOUT YOU, A Bathing Ape (BAPE),
Alles, Acne Studios, Amichi, Agatha, A.P.C., Avec, Alpinestars, Apart,
Accessoires, Arc'teryx, Avengers, Autre Ton, Alvaro Moreno, ardene, Alvi,
AYBL, Afibel, Atlas for Men, Anthropologie, Adanola, Alpha Industries,
Asmodee, Aesthetic, Art, Amélie & Amélie, Alain Manoukian, adidas
Superstar, Antonelle, ARNE, Alphabet, Autre Chose, Atlas, Armand Thierry,
Agatha Ruiz de la Prada, Alpine PRO, Anne Weyburn, AMBIKA, Arizona, Active
Wear, Avant Première, angry birds, Akè, Anti Blue, anello, and, Arsenal,
adidas Stan Smith, Armedangels, Altaya, Active, Agnes b, adopt’,
Activision, ara, Armor-Lux, AMI, Armani Junior, Affenzahn, Aston Martin,
Artisan, Åhléns, Almatrichi, Avenue, Angel, Animal Crossing, Australian,
Ativo, Asian, Atelier, Autry, AX, Aspesi, Accessories, Active Touch, Alto,
Alba, Acero, Anine Bing, attentif, Ale-Hop, ANNA, Asterix, Albano, Ana
Sousa, Athlitech, Angels, Army, Arcopal, Ann Taylor, ALE, Ann Christine,
Antea, Auzou, ALEXANDER, Ami Paris, Avene, Antik Batik, Akoz, Anna Karel,
Affinités, AllStar, Affliction, Amnesia, Artesano, Aubade, Aeronautica
Militare, AJC, Axel Arigato, Antica Sartoria, Alexander Wang, Azzaro,
Amitié, Amazon Essentials, Alesya, Alviero Martini 1a Classe, Anthology,
Arthur & Aston, Adrianna Papell, american outfitters, Agathe Velmont,
Aster, Aniye By, Ashley Brooke, Artesania, Admiral, A.S.98, ALBA MODA,
Aquascutum, AnnaRita N, Amy Gee, amiibo, Atos Lombardini, ASOS Petite,
ASSOS, Arkitect, Ariana Grande, AsYou, Anekke, Angelcare, Amiri, AC/DC, Amy
& Ivy, Armani Collezioni, Aim'n, ACTION BOY, Artigiano, Angela Thompson,
Aubert Concept, Aubert, Anita, adams, Arrow, Alinea, ARMISTICE, Anne Klein,
Answear, ASOS Maternity, Alberta Ferretti, Always Do What You Should Do,
Armée de Terre, aden + anais, Aaiko, Alpina, Andy & Lucy, Airfield,
appel's, ANANY, Alma en Pena, Animaux, Aigner, Adrenalyn, Anastasia Beverly
Hills, Articles, Anne Geddes, Audi, American Club, Authentic Style, Alpine,
C&A, Camaïeu, Cache Cache, Calvin Klein, Converse, Cool Club, Carhartt,
Champion, Celio, Chicco, CROPP, Catimini, Crocs, Creeks, Clockhouse,
Calzedonia, Cyrillus, Clarks, COS, Comptoir des Cotonniers, Caroll,
Coccodrillo, Crivit, Clementoni, CUIR, Calliope, Cop Copine, Chanel,
Cortefiel, Coast, Costes, Carter's, Columbia, Claudie Pierlot, Claire's,
COQUETTE, Carpisa, CoolCat, Chaussea, Cubus, Conbipel, Canda, Cecil,
Captain Tortue, Collusion, Collection, Cars, Cider, Chipie, Cedar Wood
State, CKS, Corteiz, Cadet Rousselle, Cover, Coque, Comma, Carrefour, C.P.
Company, Complices, CARRY, Colours of the World, Cherokee, Cath Kidston,
Campus, Calvin Klein Jeans, Cargo, Cameo Rose, Coach, Chevignon, CCC,
Camomilla, CMP, Coca-Cola, Carvela, Colloseum, CASIO, Chloé, Coccinelle,
Christine Laure, CM, Crane, Cotton Club, CASA, COLMAR, Coton, Chi Chi
London, Catwalk, Cotone, Carolina Herrera, Christian Louboutin, Carrera,
Camper, Cybex, CafèNoir, Cacharel, Closed, Chapter Young, Cream, Cardigan,
Cheap Monday, Cotton On, Club L, Cars Jeans, Clarins, Clayton, Cotton &
Silk, Craft, Charm, CASSIS, Céline, Capsule, Candida, Cupshe, Canada Goose,
CHATTAWAK, Charanga, Cotton Traders, Caprice de Fille, Charles Vögele,
Coline, CHIC, C.F.K. Country For Kids, Collezione, Clinique, Canterbury,
Charlotte Tilbury, Colline, Colourful Rebel, Comme des Garçons, Coconuda,
Cotélac, Compania Fantastica, Corolle, Caprice, Cute, Carhartt WIP, Cupcake
Couture, CycleBand, Craghoppers, Carrement Beau, Caramelo, Case, Calin
Kalin, CROOP, Cashmere, Cocoon, Christian Lacroix, Custo Barcelona,
CIMARRON, Cherry Koko, Charlie & Prune, Cuddles & Smiles, Charles Tyrwhitt,
Camp David, Caroline Biss, Casablanca, Cerruti, Cocomore, Canpol Babies,
Chic Me, Casual by Gémo, Cloothes, Cosmoparis, Closet, CODE, Casual,
Classic, Clara Vitti, Crystal, Christian Berg, Cartier, Corina, Collectif,
Chasin', Cerise Blue, Chiara Ferragni, Cabaïa, Carlsberg, Chantelle,
Cambio, Confetti, Coconut, Canada House, Caudalie, COLLAR, Couture Candy,
Chelsea, Cristal, Cartoon, Coveri, Cérémonie, CENSORED, CAT, Cross, Club L
London, CELOP, Collection U, C'est beau la vie, Camel, Calcio, Castore,
Custo, Charlior, CHICAPRIE, Cycle, C'M Paris, Cluse, Camel Active, Crazy
Factory, Crew, Carré Blanc, Crosshatch, Clayeux, Centrakor, Calamaro,
Cotton, Castañer, CLUB London, Coolway, CHERRY, Caractère, Citizen,
Custommade, CKH Clockhouse, Colombia, Cat & Jack, Charlie & Friends,
Charlotte Russe, Conte of Florence, Chillin, Capelli, C&A Baby Club,
Caterpillar, Café Coton, Charlott' Lingerie, Cinque, Cable, Cuero, Cult,
Disney, Decathlon, Du Pareil au Même, Desigual, Dorothy Perkins, Diesel,
Donna, Dr. Martens, Domyos, Denim Co, Disney Baby, DopoDopo, Denim,
diverse, DKNY, Dickies, Dolce & Gabbana, Devred, Dsquared2, Dior, De,
Debenhams, Djeco, Damart, DDP, DESTINATION, Deichmann, Diadora, Dirkje,
Dunnes Stores, DeeZee, DIM, Dragon Ball, DC, Denny Rose, Disney x Primark,
Diddl, Disneyland Paris, Dune, Des Petits Hauts, Dockers, DonDup, Dixie,
Defacto, Don't Call Me Jennyfer, Darjeeling, D&G, Dunnes, Deeluxe, Dare2B,
Dune London, Dazy, DC Shoes, Daily paper, David Jones, Didi, Daniel
Hechter, Disney × Pixar, Dainese, Dunelm, Dunlop, Double Agent, Derhy,
Drôle de Copine, Debut, Drykorn, Daisy Street, Dujardin, Dyson, Daniel
Wellington, Doudou et Compagnie, D.D. Step, Daphnea, DM, DC Comics, Diamond
Painting, Daxon, Dept, Deluxe, Daniele Alessandrini, Despicable Me Minion
Made, Dulces, Dragon Ball Z, Douglas, Didriksons, Diane von Fürstenberg,
Dama, DPM By Depech Mod, Dreamworks, Dolce, Dorotennis, Dodipetto, Diamond,
DoDo, Dino, Daysie, Dustin, DEVERNOIS, Dirndl, DATCH, Dakine, di, Dolce
Petit, Dodie, DISTRIKT NØRREBRO, D-zine, Décimas, DANI, Dimensione Danza,
Disney Princess, Dancing Leopard, Dragon, Doña Carmen, Do, Diva, Doomoo,
Dimo, Deco, Ducati, dilling, Dance, Dolls Kill, Danity, Dressmann, Denham,
Denim Collection, DIFFERENT, DENIM JEANS, Demon Slayer, Demar, Dolores
Promesas, Dora the Explorer, Danza, Dolls, Disana, Daim, DeAgostini, Dolly
Wears, Dorking, Done by Deer, DEHA, Dinosaur, DADA, Dolce Vita,
Diamantique, Dayaday, Dandelion, Döll, diset, Derby, Doppelgänger, Disney X
C&A, Darling, Domino, Dedoles, DREAM, Duet A&M, DécoTime, DPM, Diana
Gallesi, Disturbia, Diamant, Dorado, Dries van Noten, Distrikt, Diplodocus,
Dri-Fit, DONSJE, Dadati, Dopo Mini, Devergo, Dove, Deuter, Dr. Scholl's,
Däumling, Donnay, DEEPLY, DJ DUTCHJEANS, DAY, Designer's, Denim Life, Donna
Piu', DOU DOU, Dobble, DIGEL, Diptyque, DORINA, Definitions, Difrax, David
Emanuel, Deby Debo, Denim 1982, D.A.T.E., Desires, D&D, Doctor Who, DAISY,
Dissident, Dan John, Donaldson, Dorabella, Die Spiegelburg, De Fursac,
DEUX, DUNS Sweden, D, Dandara, Danskin, Dope, Dreambaby, Disney at George,
DI FONTANA, Dilvin, Defonseca, DLSB, Diane Laury, Decenio, Dreambee,
Deeluxe 74, DinSko, Douceur d'intérieur, Dorko, Dr. Kid, Day-Vine, Dombi,
Damsel in a Dress, Dutchy, Dressmezee, Duck, Dr Brown's, DOC, Danefae,
Danhen, Donna Karan, Decoration, Down Up, DECA, DELSEY, Daily Aesthetikz,
Esprit, Etam, Esmara, Ergee, Ellesse, EDC by Esprit, El Corte Inglés,
Emporio Armani, Even&Odd, Easy Wear, érama, Elisabetta Franchi, Eastpak,
Ernsting's family, Energetics, Elefanten, Element, EGO, Early Days, ECCO,
Eden Park, ELEGANTE, Everlast, Essentiel, ELLE, Etirel, Engelbert Strauss,
Educa, Evans, Estée Lauder, Envie de Fraise, Eksept, Eldys, Excellent,
Escada, Ergobaby, Easy Clothes, Extenso, ENGLAND, Essence, Emery Rose,
Elite, Europe Kids, Ellos, EL GANSO, ever.me, ELORA, Enrico Coveri,
Essentiel Antwerp, Easy, ET, Encuentro, Expresso, Express, Ed Hardy, Emidio
Tucci, Etro, Emoji, Essential, E-vie, Energie, Enchantimals, ETUI, Erreà,
Emma & Ella, EMP, Elena Miro, Edited, Et Vous, Envy, EMO, Esotiq, Enjoy,
endo., EA, Elemis, Erima, Eva & Lola, Ever Pretty, Emel, Egree, ellepi,
Espadrilles, és, Extyn, Equi Théme, Eterna, Engel, EIGHT PARIS, Elogy,
Everest, Eco, Elsa, Evisu, Edwin, Eat Ants, Empik, EAST, Exclusive,
Eseoese, ECKO UNLTD., EA Sports, ERYNN, Eden & Victor, EDJI, eden, Evita,
Ekyog, Elodie Details, Eliane et Lena, Eichhorn, Ecoiffier, Elli White,
Ermenegildo Zegna, Emu, Elsy, Eight2Nine, Exquiss's, Este, El Naturalista,
Envii, Emoi by Emonite, Enzoria, Emile et Rose, Eleven, Exé, Eddie Bauer,
Eros, Eiki, Et Compagnie, Esprit Collection, Ermanno Scervino, Episode,
Erborian, Elisa Cavaletti, Etnies, e.l.f., Ella, Eider, Eastex, Ea Games,
Elégance, Escandelle, Emma, EsQualo, Elegant, Elizabeth Arden, EMC, Eric
Bompard, ECHO, El, Early Learning Centre, ELEMENTS, Emma Bridgewater, En
Fant, Eksept by Shoeby, Elizabeth Stuart, Elle est où la Mer, Emma
Pernelle, Edge, Emile et Ida, Eveline, Emilio Pucci, Ema blues, E-Bound,
EWM, Etnica, emo.i, Emporio, Edan, Essie, Elvira, elefun, Evento, Eva
Kayan, Encore, Eternel, Elisa Landri, EDEIS, Escada Sport, EDC Brand,
Elodie, El Nino, Endura, Extra Me, edikted, Eucerin, e(x)it, Eva Minge,
Ernest, estrada, ELENZA By L&L, Eva, Ethnic, Eres, Editions Atlas,
Escorpion, engbers, Esther, Eureka, Energy, Énfasis, Emamoda, Eskimo, E-vie
Angel, ELIZABETH, Extasy, Ergeenomixx, Ecoalf, ENSORED, Etxart & Panno,
ELBRUS, Ergobag, Efteling, Elvie, Essenza, Elise Ryan, EAGLEMOSS
COLLECTIONS, El caballo, Extreme, ELC, Epop, Equilibre, Excellence,
EXPOSURE, Everton, EMU Australia, Electric, Exacompta, Everlane, Enzo,
Everyday, Ewa Klucze, ewers, Evis, EYE, Edge Street, ERFO, F&F, FILA,
Funko, FB Sister, Forever 21, Fisher Price, FatFace, French Connection,
Fred Perry, Fashion, Fagottino, Fred & Flo, Feetje, Fouganza, Fórmula
Joven, Fossil, Firefly, Frozen, FIFA, Fruit of the Loom, Fox & Bunny,
Fashion Private Company, Fishbone, Filou & Friends, FSBN, Fantaisie, Fendi,
Firetrap, Frugi, Furla, Fornarina, Fashion Nova, Ferrari, Free People,
Fabrication Artisanale, Fiesta, Fortnite, Flamenca, Freegun, Fisherfield,
Fashion Jewelry, Fjällräven, Franklin & Marshall, Freddy, Freeman T.
Porter, Fracomina, Fay, Freestyle, Fabletics, Fórmul@, Faith, Farah, Fox,
FC Barcelona, Foto, F&F Kids, flame, Fait-Maison, Fiorella Rubino, Femme
Luxe, Froddo, Fransa, FPC, Footkorner, Fabienne Chapot, F**K, Fashion
Union, Florence + Fred, Festa, Friboo, Fiorelli, Festina, Fantasia,
falcotto, Freemouss, Forever, Freequent, FREE LANCE, Fitbit, Flying Tiger,
Filippa K, F.R.I.E.N.D.S, Fischer, Fashion Express, Façonnable, Fun&Fun,
FitFlop, Flamant Rose, Flamenco, Forever Unique, Fiorucci, Fiore, FIMO,
Famosa, Fred Mello, Freya, FFF, Finkid, Fred & Ginger, Follow Me, Fixoni,
Father & Sons, Fenn Wright Manson, Francoise Saget, Forever New, FC Bayern
München, Fish & Chips, Fosco, Flora & Co, Fly, Freesoul, Fly London, FRAU,
Fancy, Fantasie, FRNCH, First, FREEMAN, FB, Fenty Beauty, F&P, FootJoy,
Furygan, Fehn, Fusalp, Fishbone Sister, Folk, Fantasy, Fear of God,
Ferrache, Frendz, Fairy, Filorga, Falcon, Falke, Fleurus, Family, Filling
Pieces, Frame, Fly Girl, Fairfax & Favor, Forclaz, Freesia, Foppapedretti,
Finery, Final Fantasy, Faded Glory, FurReal, Florence, Fruit de Ma Passion,
Frilivin, Fabiani, fugitive, Friends Like These, FRUTTA, Fratelli Rossetti,
Fleur, FCB, Forpen, Finger in the nose, Forecast, Frida, Flinq, Fame,
Flavio Castellani, Felix Bühler, FlashLights, Forma, FAGUO, Fgm04, Fashion
Jeans, FNAC, F1, Falconeri, Fresh Made, Fireman Sam, Flam Mode, Frank
Walder, Francesco Milano, Find, Frankie Garage, Foque, Farmasi, Feraud,
Flower, FairyLoot, Freebird, Five, Falmer Heritage, Fuchs Schmitt, Frime,
Fred de la Bretoniere, Frankie Morello, Farfallina, Floreiza, floriane,
Freda, Flamingo, FIT, Fever, Fred, Face, Floryday, FLUID, Fiorella di
Verdi, Fritzi aus Preußen, Fare, Fashion New York, Falmer, Fred Sabatier,
FitZ, FABRIC, Forti, Ferre, Flash, Farfalla, Fenty, Fde la passion, Frank
Lyman, Ford, Forever Folie, Fashion Studio, folia, Francomina, Femestage,
Findlay, Firenze, Fresh, FOR, FUBU, FC, Foot Locker, Figleaves, Francesco
Biasia, Fluffy, Feuerwehrmann Sam, Finest, fashionova, Flo, Gémo, GUESS,
George, GAP, George at ASDA, Geox, Gymshark, G-Star, Gucci, Graceland,
Grain de Malice, Grain de Blé, Gina Tricot, GANT, Gildan, Giacca, Garcia,
Galeries Lafayette, Gerard Darel, G-Star RAW, Girls, Gocco, Gerry Weber,
Glamorous, Gabor, Green Coast, GAS, Gate, Gaudi, Ganni, Gina Benotti,
Givenchy, Gina, Gaastra, GapKids, Goliath, Geisha, Grace & Mila, GYMP, Go
Sport, Gold, GiFi, Garcia Jeans, Greenpoint, Gioseppo, Geographical Norway,
Golden Goose, Gino Rossi, Game, Green, Guerlain, Gym King, Giochi Preziosi,
Games Workshop, Garmin, Gilly Hicks, Giuseppe Zanotti, Guru, Guts & Gusto,
Goa, GHD, GRANDS BOULEVARDS, Gianfranco Ferré, Gerard Pasquier, Gameboy,
Guess by Marciano, Girl in Mind, Gaëlle Paris, Garnier, Givova,
Goldenpoint, Gate Woman, Georges Rech, Giorgia, Gentleman Farmer, Gymboree,
Gola, Gormiti, Golden Days, Gym Glamour, Globe, Gipsy, GIRL, GBB, George
Gina & Lucy, Giorgio, Giorgia & Johns, G-Shock, Gigamic, Gattinoni,
Glitter, Guess Jeans, Gian Marco Venturi, Gloria Ortiz, Glamour, GYM,
Gallantry, Ghost, Gorgeous, Goki, Great Plains, Goodies, Gallery, GCDS,
Gelert, Galaxy, Gold & Silver, Gutteridge, Garancia, Gatta, Golden Lady,
GLOBO, Guy Laroche, Grobag, Giesswein, Grünland, Gina Laura, Gudrun Sjödén,
Glowrias, Grace, Gestuz, Garage, GAUDI JEANS, Gaëlle, Grey Wolf, Grace
Karin, Golddigga, Gang, Grigio, GAMECUBE, Garvalín, Gazelle, Groggy by jbc,
Glass, Groggy, Gina Bacconi, Generation, Guinness, Girl2Girl, GF Ferre,
Giro, Geneva, GIRLS ON FILM, Gadea, Gsus, Goodin, Genius, Goula,
Goosecraft, Gamex, gardeur, G-MAXX, Grafix, Garconne, Gibsons, Gianni
Chiarini, Glo-Story, Gaialuna, Gorjuss, Goddess Story, GR, giracoo, Gabs,
GB, Goose & Gander, GOOD FOR NOTHING, Gore Tex, Grand & Hills, GELCO, Good
Look, Giacomo Conti, gabriella vicenza, Grimey, GALLO, Gien, Giordani,
Gabby's Dollhouse, Glassons, Gai Mattiolo, Golfino, Gigue, Gov Denim, Game
of Thrones, Golden Live, GRA, Garanimals, Galt, Guzzini, GUM, GRANNA,
Gioielli, G&G, G Kids, Gianni Lupo, Gugguu, Graine de Rêve, Graco, Gio
Cellini, Grand Voile, GDM, GRO, Genuins, Gil Bret, Gas Bijoux, Goddiva,
G-Smack, Gallery Dept., Gamin Gamine, Gaia, Griffon, Görtz, Givana, GOGO,
GONE by Gemo, Gründ, Gilbert, Google, GARDEN, Gambettes Box, Garfield, Gray
Label, g:21, Gatti, goldsmith, Good Smile Company, Gore Wear, Georgia Rose,
GIRANDOLA, GymBeam, Gertrude, Giovanni, Giada, Giordano, GUL, GREGOR,
Gianvito Rossi, Giovanni Galli, Green ICE, Goddess, H&M, Hollister, Hema,
Hugo Boss, H&M Divided, House, Harry Potter, Hello Kitty, Hasbro, Hot
Wheels, Havaianas, Hogan, Hummel, Hobbs, H&M Mama, Hallhuber, Haba,
Hollister & Co, Handgemaakt, Helly Hansen, Hilfiger Denim, House Brand,
Hermès, Harley Davidson, Harmont & Blaine, Hecho a Mano, Hype, Hailys,
Head, Hippie, Hard Rock Café, Hush, Hunter, Hackett, House of CB, Hand
Knitted, Hard Rock, H&M L.O.G.G., Hachette, Hoka, Hoodrich, histoire d'or,
Hugo, heine, Huawei, Hell Bunny, Hause, Hi-Tec, HUF, Heelys, Hush Puppies,
Hispanitas, Hurley, Huda Beauty, Hublot, Hotter, Hoss Intropia, Hello Miss,
Henry Cotton´s, Happiness, home&you, Hipanema, HÖGL, Henri Lloyd, H&M
Sport, Hape, Halara, Hust & Claire, Hangar 86, Hampton Republic, Hair,
High, Hampton Bays, H&M Basic, Happy House, Homme+, Hartford, Hatchimals,
Hauck, Hat, HEM, Handmade Beauty, Harrods, Herschel, hama, Heyraud, Hess
Natur, Holly & Whyte, Hatley, Hanes, Hope, hp, Hexagona, Hennes Collection,
Hera, H2O, Home Bargains, happy girls, Hawkers, H-Landers, heavy tools,
Hachette Jeunesse, Hackett London, HOUSE OF JAMIE, Heritage, Haglöfs, Happy
Kids, Hot Tuna, Holiday, Hobby Horse, H&M Home, Huggies, Hoppediz, Harris
Wilson, HKM, Holland Cooper, Herrlicher, Human Nature, Happy Girls Club by
C&A, Hoss, HAPPY, H.I.S, Habitat, Heart, Hudson, Horze, Happy Socks, Holz,
Honda, HV Polo, Hey Duggee, Harry Styles, Hawes & Curtis, House of Denim,
H&D, Hero Seven, Helmut Lang, Holly Bracken, Halo, Haix, Home Creation,
Hobbycraft, Hippocampe, Helen, Harper & Yve, Hatier, Hanny Deep, Headu,
HIP, Hannah, HUGO Hugo Boss, Haydi, Hope & Ivy, Heineken, HELLINE, Highly
Preppy, Hilde & Co, HJC, Hennes, Heartbreak, H&M Conscious, House of
Fraser, H&L, HOFF, HOOPS, Henleys, Henry Holland, Hue, Harmony, Haribo,
Hearts & Roses, HDM, HAPPY STAR, Happymum, H.Samuel, Histoire d'Ours, HYMN,
Heron Preston, Harris Tweed, Hamac, Hammerschmid, Herno, Hollywood, Hirsch,
Hi Gear, Hip & Hopps, Hannah Montana, Hakei, Hobby, Husky, Harris & Lewis,
HIIT, Hello Moon Shop, HONOR, Helvetica, Harry's Horse, Home & Deco,
HelloBody, HAVEONE, Happy Horse, HF, Hozone, Harvard, Herlaine, Himalaya,
Herlitz, Hana, HYBRID, Hod, Hein-Gericke, Howick, Humanoid, Holyfield,
Holly & Joey, Huit, Hamaki - Ho, Hamilton, Helena Sorel, huari, Happy Meal,
Happyland, HUB, Heavenly Feet, Honey Punch, Hourglass, Hotel Particulier,
Hale Bob, Heidi Klum, HKMX, Hug & Clau, Hollywood Dream, HHG, Hartan,
Horsefeathers, Head Over Heels By Dune, Inconnu, In Extenso, IKKS, Iné,
IKEA, Intimissimi, Impidimpi, I Saw it First, Influx, In The Style, Inside,
Independent, Imperial, Isabel Marant, ICHI, IDEXE', I Do, ici et
maintenant, Italy Moda, Indian, Italia, Intersport, Icepeak, it Hippie, I
am, I.Code, Iceberg, iets frans..., Ideal Of Sweden, Intrend, Il Gufo,
Intextenso, Ipanema, Ideal, IZAC, IGOR, IRO, Influence, Infinity, Indigo,
Invicta, IVIVI, Ina, Ice Watch, intermarché, INTEX, Italian Style, InWear,
Irregular Choice, Identic, Isotoner, Ideal shoes, Ivy Park, Infantino, iTS,
IXON, Indian Blue Jeans, IANA, IXOO, iBlues, Indiska, Ikita, Interdit de me
gronder, Inglesina, Izabel London, Igi&Co, I love girlswear, iELM, INC, In
April 1986, ICON, IDK, Imps & Elfs, Isabel Marant Étoile, Inter, ikebana,
Izabel, Internacionale, In Vogue, Iron Fist, Infinity Kids, Iwie, ICIW,
INOX, Isle, IUTER, Indi & Cold, Inesis, IZIPIZI, Issey Miyake, IMC Toys,
Imaginarium, Inditex, iEFiEL, Inuovo

nonnullish ***@***.***> escreveu (quinta, 13/06/2024 à(s)
16:39):

**Comment by nonnullish** [comment]
thanks! will look into it

**Comment by nonnullish** [comment]
okay, tested it & made changes :) you can redownload the extension now
I'm assuming you're using Chrome - on Firefox it seemed to work without any modifications
this can make the page slow so I would recommend limiting the list, but it should work now as it is

also, "h&m" will cover "h&m mama", "h&m divided", "h&m basic", etc etc :) as long as a part of the brand name is specified then the item will be hidden

**Comment by studystudy92** [comment]
Thank you I will try it again

Can I ask if you don't mind, does the extension exclude searches of the
words exclusively inputted on the box "brand" or will it exclude also
searches of that word if written in the item title?

Thanks :)

**Comment by studystudy92** [comment]
When I exclude many brands , the search starts hiding brands that are not
on my list for some reason,  very weird :/

**Comment by studystudy92** [comment]
For example if I exclude brand : "art" , it will automatically exclude
brand Dr. Martens , because there is the word art on it,  is there a work
around?

**Comment by nonnullish** [comment]
> does the extension exclude searches of the words exclusively inputted on the box "brand" or will it exclude also searches of that word if written in the item title?

only the brand field!

> if I exclude brand : "art" , it will automatically exclude
brand Dr. Martens , because there is the word art on it,  is there a work
around?

yeah, that’s probably why. when I have some more time I’ll add a setting to toggle between exact matching (so that only brand “art” would get hidden) and the way it is now :)

**Comment by studystudy92** [comment]
That would be amazing 👏 would you let me know when you get the chance to
do it , really appreciate it :)

**Comment by studystudy92** [comment]
Hello

I was just wondering if you managed to fix this issue?

Kind regards

**Comment by nonnullish** [comment]
hey @studystudy92, not yet, maybe next weekend! I'll make sure you'll be notified

**Comment by nonnullish** [comment]
hey @studystudy92 I added the toggle :) it's available now

**Comment by studystudy92** [comment]
Hello,

Would you be able to create same app , but instead of filtering by brands ,
it would filter by keywords on the description? For example , for brand
nike I don't want to see listings of jackets.

Would this be doable? I would be able to pay for this project if you are
interested.

Let me know before I reach to other coders

Thanks :)

**Comment by nonnullish** [comment]
hi @studystudy92, I don't think that's possible because there's no access to this data from the search results view
